---
elasticsearchHosts: "http://elasticsearch:9200"

replicaCount: 1

extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=1800"

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.5.1"
  pullPolicy: IfNotPresent

resources:
  # Adjust resources as needed
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

protocol: http
serverHost: "0.0.0.0"
httpPort: 5601

healthCheckPath: "/app/kibana"

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

updateStrategy:
  type: "Recreate"

service:
  type: ClusterIP
  port: 5601
  httpPortName: http
  annotations: {}
  labels: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: kubernetes.docker.internal
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
